<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_remember_key' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Apr 30 19:05:46 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfGuardPlugin.lib.model
 */
class sfGuardRememberKeyQuery extends BasesfGuardRememberKeyQuery {

} // sfGuardRememberKeyQuery
