<?php



/**
 * This class defines the structure of the 'evaluation' table.
 *
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Apr 30 19:09:40 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class EvaluationTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EvaluationTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('evaluation');
		$this->setPhpName('Evaluation');
		$this->setClassname('Evaluation');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('SITE_ID', 'SiteId', 'INTEGER' , 'site', 'ID', true, null, null);
		$this->addForeignPrimaryKey('ECRITERIA_ID', 'EcriteriaId', 'INTEGER' , 'ecriteria', 'ID', true, null, null);
		$this->addForeignPrimaryKey('METRIC_ID', 'MetricId', 'INTEGER' , 'metric', 'ID', true, null, null);
		$this->addColumn('VALUE', 'Value', 'INTEGER', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('Site', 'Site', RelationMap::MANY_TO_ONE, array('site_id' => 'id', ), 'CASCADE', null);
		$this->addRelation('Ecriteria', 'Ecriteria', RelationMap::MANY_TO_ONE, array('ecriteria_id' => 'id', ), 'CASCADE', null);
		$this->addRelation('Metric', 'Metric', RelationMap::MANY_TO_ONE, array('metric_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // EvaluationTableMap
