<?php



/**
 * Skeleton subclass for representing a row from the 'criteria' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Apr 30 19:05:45 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Criteria extends BaseCriteria {

} // Criteria
