<?php



/**
 * Skeleton subclass for performing query and update operations on the 'evaluation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Apr 30 19:05:45 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EvaluationPeer extends BaseEvaluationPeer {
	static public function getInstance(Ecriteria $ecriteria) {
		$site = SiteQuery::create()
			->findOneByUrl(sfContext::getInstance()->getUser()->getAttribute('url'));
		$ret = self::retrieveByPk($site->getId(), $ecriteria->getId(), $ecriteria->getMetricId());
		if(empty($ret)) {
			$ret = new Evaluation();
			$ret->setSite($site);
			$ret->setEcriteria($ecriteria);
			$ret->setMetric($ecriteria->getMetric());
			$ret->save();
		}
		return $ret;
	}
} // EvaluationPeer
