<?php


/**
 * Base class that represents a query for the 'criteria' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Apr 30 19:05:45 2012
 *
 * @method     CriteriaQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     CriteriaQuery orderByMetricId($order = Criteria::ASC) Order by the metric_id column
 * @method     CriteriaQuery orderByDescription($order = Criteria::ASC) Order by the description column
 * @method     CriteriaQuery orderByFormField($order = Criteria::ASC) Order by the form_field column
 *
 * @method     CriteriaQuery groupById() Group by the id column
 * @method     CriteriaQuery groupByMetricId() Group by the metric_id column
 * @method     CriteriaQuery groupByDescription() Group by the description column
 * @method     CriteriaQuery groupByFormField() Group by the form_field column
 *
 * @method     CriteriaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     CriteriaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     CriteriaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     CriteriaQuery leftJoinMetric($relationAlias = null) Adds a LEFT JOIN clause to the query using the Metric relation
 * @method     CriteriaQuery rightJoinMetric($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Metric relation
 * @method     CriteriaQuery innerJoinMetric($relationAlias = null) Adds a INNER JOIN clause to the query using the Metric relation
 *
 * @method     CriteriaQuery leftJoinEvaluation($relationAlias = null) Adds a LEFT JOIN clause to the query using the Evaluation relation
 * @method     CriteriaQuery rightJoinEvaluation($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Evaluation relation
 * @method     CriteriaQuery innerJoinEvaluation($relationAlias = null) Adds a INNER JOIN clause to the query using the Evaluation relation
 *
 * @method     Criteria findOne(PropelPDO $con = null) Return the first Criteria matching the query
 * @method     Criteria findOneOrCreate(PropelPDO $con = null) Return the first Criteria matching the query, or a new Criteria object populated from the query conditions when no match is found
 *
 * @method     Criteria findOneById(int $id) Return the first Criteria filtered by the id column
 * @method     Criteria findOneByMetricId(int $metric_id) Return the first Criteria filtered by the metric_id column
 * @method     Criteria findOneByDescription(string $description) Return the first Criteria filtered by the description column
 * @method     Criteria findOneByFormField(string $form_field) Return the first Criteria filtered by the form_field column
 *
 * @method     array findById(int $id) Return Criteria objects filtered by the id column
 * @method     array findByMetricId(int $metric_id) Return Criteria objects filtered by the metric_id column
 * @method     array findByDescription(string $description) Return Criteria objects filtered by the description column
 * @method     array findByFormField(string $form_field) Return Criteria objects filtered by the form_field column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseCriteriaQuery extends ModelCriteria
{
	
	/**
	 * Initializes internal state of BaseCriteriaQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Criteria', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new CriteriaQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    CriteriaQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof CriteriaQuery) {
			return $criteria;
		}
		$query = new CriteriaQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj = $c->findPk(array(12, 34), $con);
	 * </code>
	 *
	 * @param     array[$id, $metric_id] $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Criteria|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = CriteriaPeer::getInstanceFromPool(serialize(array((string) $key[0], (string) $key[1]))))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(CriteriaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    Criteria A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT `ID`, `METRIC_ID`, `DESCRIPTION`, `FORM_FIELD` FROM `criteria` WHERE `ID` = :p0 AND `METRIC_ID` = :p1';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key[0], PDO::PARAM_INT);
			$stmt->bindValue(':p1', $key[1], PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new Criteria();
			$obj->hydrate($row);
			CriteriaPeer::addInstanceToPool($obj, serialize(array((string) $row[0], (string) $row[1])));
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    Criteria|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(array(12, 56), array(832, 123), array(123, 456)), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		$this->addUsingAlias(CriteriaPeer::ID, $key[0], Criteria::EQUAL);
		$this->addUsingAlias(CriteriaPeer::METRIC_ID, $key[1], Criteria::EQUAL);

		return $this;
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		if (empty($keys)) {
			return $this->add(null, '1<>1', Criteria::CUSTOM);
		}
		foreach ($keys as $key) {
			$cton0 = $this->getNewCriterion(CriteriaPeer::ID, $key[0], Criteria::EQUAL);
			$cton1 = $this->getNewCriterion(CriteriaPeer::METRIC_ID, $key[1], Criteria::EQUAL);
			$cton0->addAnd($cton1);
			$this->addOr($cton0);
		}

		return $this;
	}

	/**
	 * Filter the query on the id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterById(1234); // WHERE id = 1234
	 * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
	 * $query->filterById(array('min' => 12)); // WHERE id > 12
	 * </code>
	 *
	 * @param     mixed $id The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(CriteriaPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the metric_id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByMetricId(1234); // WHERE metric_id = 1234
	 * $query->filterByMetricId(array(12, 34)); // WHERE metric_id IN (12, 34)
	 * $query->filterByMetricId(array('min' => 12)); // WHERE metric_id > 12
	 * </code>
	 *
	 * @see       filterByMetric()
	 *
	 * @param     mixed $metricId The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterByMetricId($metricId = null, $comparison = null)
	{
		if (is_array($metricId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(CriteriaPeer::METRIC_ID, $metricId, $comparison);
	}

	/**
	 * Filter the query on the description column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByDescription('fooValue');   // WHERE description = 'fooValue'
	 * $query->filterByDescription('%fooValue%'); // WHERE description LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $description The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterByDescription($description = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($description)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $description)) {
				$description = str_replace('*', '%', $description);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CriteriaPeer::DESCRIPTION, $description, $comparison);
	}

	/**
	 * Filter the query on the form_field column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByFormField('fooValue');   // WHERE form_field = 'fooValue'
	 * $query->filterByFormField('%fooValue%'); // WHERE form_field LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $formField The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterByFormField($formField = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($formField)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $formField)) {
				$formField = str_replace('*', '%', $formField);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CriteriaPeer::FORM_FIELD, $formField, $comparison);
	}

	/**
	 * Filter the query by a related Metric object
	 *
	 * @param     Metric|PropelCollection $metric The related object(s) to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterByMetric($metric, $comparison = null)
	{
		if ($metric instanceof Metric) {
			return $this
				->addUsingAlias(CriteriaPeer::METRIC_ID, $metric->getId(), $comparison);
		} elseif ($metric instanceof PropelCollection) {
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
			return $this
				->addUsingAlias(CriteriaPeer::METRIC_ID, $metric->toKeyValue('PrimaryKey', 'Id'), $comparison);
		} else {
			throw new PropelException('filterByMetric() only accepts arguments of type Metric or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the Metric relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function joinMetric($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Metric');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Metric');
		}

		return $this;
	}

	/**
	 * Use the Metric relation Metric object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MetricQuery A secondary query class using the current class as primary query
	 */
	public function useMetricQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinMetric($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Metric', 'MetricQuery');
	}

	/**
	 * Filter the query by a related Evaluation object
	 *
	 * @param     Evaluation $evaluation  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function filterByEvaluation($evaluation, $comparison = null)
	{
		if ($evaluation instanceof Evaluation) {
			return $this
				->addUsingAlias(CriteriaPeer::ID, $evaluation->getCriteriaId(), $comparison);
		} elseif ($evaluation instanceof PropelCollection) {
			return $this
				->useEvaluationQuery()
				->filterByPrimaryKeys($evaluation->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterByEvaluation() only accepts arguments of type Evaluation or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the Evaluation relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function joinEvaluation($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Evaluation');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Evaluation');
		}

		return $this;
	}

	/**
	 * Use the Evaluation relation Evaluation object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    EvaluationQuery A secondary query class using the current class as primary query
	 */
	public function useEvaluationQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinEvaluation($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Evaluation', 'EvaluationQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Criteria $criteria Object to remove from the list of results
	 *
	 * @return    CriteriaQuery The current query, for fluid interface
	 */
	public function prune($criteria = null)
	{
		if ($criteria) {
			$this->addCond('pruneCond0', $this->getAliasedColName(CriteriaPeer::ID), $criteria->getId(), Criteria::NOT_EQUAL);
			$this->addCond('pruneCond1', $this->getAliasedColName(CriteriaPeer::METRIC_ID), $criteria->getMetricId(), Criteria::NOT_EQUAL);
			$this->combine(array('pruneCond0', 'pruneCond1'), Criteria::LOGICAL_OR);
		}

		return $this;
	}

} // BaseCriteriaQuery