<?php


/**
 * Base class that represents a row from the 'evaluation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Apr 30 19:09:40 2012
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseEvaluation extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'EvaluationPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EvaluationPeer
	 */
	protected static $peer;

	/**
	 * The value for the site_id field.
	 * @var        int
	 */
	protected $site_id;

	/**
	 * The value for the ecriteria_id field.
	 * @var        int
	 */
	protected $ecriteria_id;

	/**
	 * The value for the metric_id field.
	 * @var        int
	 */
	protected $metric_id;

	/**
	 * The value for the value field.
	 * @var        int
	 */
	protected $value;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Site
	 */
	protected $aSite;

	/**
	 * @var        Ecriteria
	 */
	protected $aEcriteria;

	/**
	 * @var        Metric
	 */
	protected $aMetric;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [site_id] column value.
	 * 
	 * @return     int
	 */
	public function getSiteId()
	{
		return $this->site_id;
	}

	/**
	 * Get the [ecriteria_id] column value.
	 * 
	 * @return     int
	 */
	public function getEcriteriaId()
	{
		return $this->ecriteria_id;
	}

	/**
	 * Get the [metric_id] column value.
	 * 
	 * @return     int
	 */
	public function getMetricId()
	{
		return $this->metric_id;
	}

	/**
	 * Get the [value] column value.
	 * 
	 * @return     int
	 */
	public function getValue()
	{
		return $this->value;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [site_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluation The current object (for fluent API support)
	 */
	public function setSiteId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->site_id !== $v) {
			$this->site_id = $v;
			$this->modifiedColumns[] = EvaluationPeer::SITE_ID;
		}

		if ($this->aSite !== null && $this->aSite->getId() !== $v) {
			$this->aSite = null;
		}

		return $this;
	} // setSiteId()

	/**
	 * Set the value of [ecriteria_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluation The current object (for fluent API support)
	 */
	public function setEcriteriaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ecriteria_id !== $v) {
			$this->ecriteria_id = $v;
			$this->modifiedColumns[] = EvaluationPeer::ECRITERIA_ID;
		}

		if ($this->aEcriteria !== null && $this->aEcriteria->getId() !== $v) {
			$this->aEcriteria = null;
		}

		return $this;
	} // setEcriteriaId()

	/**
	 * Set the value of [metric_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluation The current object (for fluent API support)
	 */
	public function setMetricId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->metric_id !== $v) {
			$this->metric_id = $v;
			$this->modifiedColumns[] = EvaluationPeer::METRIC_ID;
		}

		if ($this->aMetric !== null && $this->aMetric->getId() !== $v) {
			$this->aMetric = null;
		}

		return $this;
	} // setMetricId()

	/**
	 * Set the value of [value] column.
	 * 
	 * @param      int $v new value
	 * @return     Evaluation The current object (for fluent API support)
	 */
	public function setValue($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->value !== $v) {
			$this->value = $v;
			$this->modifiedColumns[] = EvaluationPeer::VALUE;
		}

		return $this;
	} // setValue()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.
	 *               Empty strings are treated as NULL.
	 * @return     Evaluation The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		$dt = PropelDateTime::newInstance($v, null, 'DateTime');
		if ($this->created_at !== null || $dt !== null) {
			$currentDateAsString = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
			if ($currentDateAsString !== $newDateAsString) {
				$this->created_at = $newDateAsString;
				$this->modifiedColumns[] = EvaluationPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.
	 *               Empty strings are treated as NULL.
	 * @return     Evaluation The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		$dt = PropelDateTime::newInstance($v, null, 'DateTime');
		if ($this->updated_at !== null || $dt !== null) {
			$currentDateAsString = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
			if ($currentDateAsString !== $newDateAsString) {
				$this->updated_at = $newDateAsString;
				$this->modifiedColumns[] = EvaluationPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->site_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->ecriteria_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->metric_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->value = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->created_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->updated_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 6; // 6 = EvaluationPeer::NUM_HYDRATE_COLUMNS.

		} catch (Exception $e) {
			throw new PropelException("Error populating Evaluation object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSite !== null && $this->site_id !== $this->aSite->getId()) {
			$this->aSite = null;
		}
		if ($this->aEcriteria !== null && $this->ecriteria_id !== $this->aEcriteria->getId()) {
			$this->aEcriteria = null;
		}
		if ($this->aMetric !== null && $this->metric_id !== $this->aMetric->getId()) {
			$this->aMetric = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EvaluationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EvaluationPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSite = null;
			$this->aEcriteria = null;
			$this->aMetric = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EvaluationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$deleteQuery = EvaluationQuery::create()
				->filterByPrimaryKey($this->getPrimaryKey());
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEvaluation:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				$deleteQuery->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEvaluation:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EvaluationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEvaluation:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(EvaluationPeer::UPDATED_AT))
			{
				$this->setUpdatedAt(time());
			}
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(EvaluationPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEvaluation:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				EvaluationPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSite !== null) {
				if ($this->aSite->isModified() || $this->aSite->isNew()) {
					$affectedRows += $this->aSite->save($con);
				}
				$this->setSite($this->aSite);
			}

			if ($this->aEcriteria !== null) {
				if ($this->aEcriteria->isModified() || $this->aEcriteria->isNew()) {
					$affectedRows += $this->aEcriteria->save($con);
				}
				$this->setEcriteria($this->aEcriteria);
			}

			if ($this->aMetric !== null) {
				if ($this->aMetric->isModified() || $this->aMetric->isNew()) {
					$affectedRows += $this->aMetric->save($con);
				}
				$this->setMetric($this->aMetric);
			}

			if ($this->isNew() || $this->isModified()) {
				// persist changes
				if ($this->isNew()) {
					$this->doInsert($con);
				} else {
					$this->doUpdate($con);
				}
				$affectedRows += 1;
				$this->resetModified();
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Insert the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @throws     PropelException
	 * @see        doSave()
	 */
	protected function doInsert(PropelPDO $con)
	{
		$modifiedColumns = array();
		$index = 0;


		 // check the columns in natural order for more readable SQL queries
		if ($this->isColumnModified(EvaluationPeer::SITE_ID)) {
			$modifiedColumns[':p' . $index++]  = '`SITE_ID`';
		}
		if ($this->isColumnModified(EvaluationPeer::ECRITERIA_ID)) {
			$modifiedColumns[':p' . $index++]  = '`ECRITERIA_ID`';
		}
		if ($this->isColumnModified(EvaluationPeer::METRIC_ID)) {
			$modifiedColumns[':p' . $index++]  = '`METRIC_ID`';
		}
		if ($this->isColumnModified(EvaluationPeer::VALUE)) {
			$modifiedColumns[':p' . $index++]  = '`VALUE`';
		}
		if ($this->isColumnModified(EvaluationPeer::CREATED_AT)) {
			$modifiedColumns[':p' . $index++]  = '`CREATED_AT`';
		}
		if ($this->isColumnModified(EvaluationPeer::UPDATED_AT)) {
			$modifiedColumns[':p' . $index++]  = '`UPDATED_AT`';
		}

		$sql = sprintf(
			'INSERT INTO `evaluation` (%s) VALUES (%s)',
			implode(', ', $modifiedColumns),
			implode(', ', array_keys($modifiedColumns))
		);

		try {
			$stmt = $con->prepare($sql);
			foreach ($modifiedColumns as $identifier => $columnName) {
				switch ($columnName) {
					case '`SITE_ID`':
						$stmt->bindValue($identifier, $this->site_id, PDO::PARAM_INT);
						break;
					case '`ECRITERIA_ID`':
						$stmt->bindValue($identifier, $this->ecriteria_id, PDO::PARAM_INT);
						break;
					case '`METRIC_ID`':
						$stmt->bindValue($identifier, $this->metric_id, PDO::PARAM_INT);
						break;
					case '`VALUE`':
						$stmt->bindValue($identifier, $this->value, PDO::PARAM_INT);
						break;
					case '`CREATED_AT`':
						$stmt->bindValue($identifier, $this->created_at, PDO::PARAM_STR);
						break;
					case '`UPDATED_AT`':
						$stmt->bindValue($identifier, $this->updated_at, PDO::PARAM_STR);
						break;
				}
			}
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
		}

		$this->setNew(false);
	}

	/**
	 * Update the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @see        doSave()
	 */
	protected function doUpdate(PropelPDO $con)
	{
		$selectCriteria = $this->buildPkeyCriteria();
		$valuesCriteria = $this->buildCriteria();
		BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
	}

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSite !== null) {
				if (!$this->aSite->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSite->getValidationFailures());
				}
			}

			if ($this->aEcriteria !== null) {
				if (!$this->aEcriteria->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEcriteria->getValidationFailures());
				}
			}

			if ($this->aMetric !== null) {
				if (!$this->aMetric->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMetric->getValidationFailures());
				}
			}


			if (($retval = EvaluationPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EvaluationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getSiteId();
				break;
			case 1:
				return $this->getEcriteriaId();
				break;
			case 2:
				return $this->getMetricId();
				break;
			case 3:
				return $this->getValue();
				break;
			case 4:
				return $this->getCreatedAt();
				break;
			case 5:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
	{
		if (isset($alreadyDumpedObjects['Evaluation'][serialize($this->getPrimaryKey())])) {
			return '*RECURSION*';
		}
		$alreadyDumpedObjects['Evaluation'][serialize($this->getPrimaryKey())] = true;
		$keys = EvaluationPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getSiteId(),
			$keys[1] => $this->getEcriteriaId(),
			$keys[2] => $this->getMetricId(),
			$keys[3] => $this->getValue(),
			$keys[4] => $this->getCreatedAt(),
			$keys[5] => $this->getUpdatedAt(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->aSite) {
				$result['Site'] = $this->aSite->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aEcriteria) {
				$result['Ecriteria'] = $this->aEcriteria->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
			if (null !== $this->aMetric) {
				$result['Metric'] = $this->aMetric->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EvaluationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setSiteId($value);
				break;
			case 1:
				$this->setEcriteriaId($value);
				break;
			case 2:
				$this->setMetricId($value);
				break;
			case 3:
				$this->setValue($value);
				break;
			case 4:
				$this->setCreatedAt($value);
				break;
			case 5:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EvaluationPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setSiteId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setEcriteriaId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setMetricId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setValue($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCreatedAt($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUpdatedAt($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EvaluationPeer::DATABASE_NAME);

		if ($this->isColumnModified(EvaluationPeer::SITE_ID)) $criteria->add(EvaluationPeer::SITE_ID, $this->site_id);
		if ($this->isColumnModified(EvaluationPeer::ECRITERIA_ID)) $criteria->add(EvaluationPeer::ECRITERIA_ID, $this->ecriteria_id);
		if ($this->isColumnModified(EvaluationPeer::METRIC_ID)) $criteria->add(EvaluationPeer::METRIC_ID, $this->metric_id);
		if ($this->isColumnModified(EvaluationPeer::VALUE)) $criteria->add(EvaluationPeer::VALUE, $this->value);
		if ($this->isColumnModified(EvaluationPeer::CREATED_AT)) $criteria->add(EvaluationPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(EvaluationPeer::UPDATED_AT)) $criteria->add(EvaluationPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EvaluationPeer::DATABASE_NAME);
		$criteria->add(EvaluationPeer::SITE_ID, $this->site_id);
		$criteria->add(EvaluationPeer::ECRITERIA_ID, $this->ecriteria_id);
		$criteria->add(EvaluationPeer::METRIC_ID, $this->metric_id);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();
		$pks[0] = $this->getSiteId();
		$pks[1] = $this->getEcriteriaId();
		$pks[2] = $this->getMetricId();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{
		$this->setSiteId($keys[0]);
		$this->setEcriteriaId($keys[1]);
		$this->setMetricId($keys[2]);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return (null === $this->getSiteId()) && (null === $this->getEcriteriaId()) && (null === $this->getMetricId());
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Evaluation (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
	{
		$copyObj->setSiteId($this->getSiteId());
		$copyObj->setEcriteriaId($this->getEcriteriaId());
		$copyObj->setMetricId($this->getMetricId());
		$copyObj->setValue($this->getValue());
		$copyObj->setCreatedAt($this->getCreatedAt());
		$copyObj->setUpdatedAt($this->getUpdatedAt());
		if ($makeNew) {
			$copyObj->setNew(true);
		}
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Evaluation Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EvaluationPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EvaluationPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Site object.
	 *
	 * @param      Site $v
	 * @return     Evaluation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSite(Site $v = null)
	{
		if ($v === null) {
			$this->setSiteId(NULL);
		} else {
			$this->setSiteId($v->getId());
		}

		$this->aSite = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Site object, it will not be re-added.
		if ($v !== null) {
			$v->addEvaluation($this);
		}

		return $this;
	}


	/**
	 * Get the associated Site object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Site The associated Site object.
	 * @throws     PropelException
	 */
	public function getSite(PropelPDO $con = null)
	{
		if ($this->aSite === null && ($this->site_id !== null)) {
			$this->aSite = SiteQuery::create()->findPk($this->site_id, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aSite->addEvaluations($this);
			 */
		}
		return $this->aSite;
	}

	/**
	 * Declares an association between this object and a Ecriteria object.
	 *
	 * @param      Ecriteria $v
	 * @return     Evaluation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEcriteria(Ecriteria $v = null)
	{
		if ($v === null) {
			$this->setEcriteriaId(NULL);
		} else {
			$this->setEcriteriaId($v->getId());
		}

		$this->aEcriteria = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Ecriteria object, it will not be re-added.
		if ($v !== null) {
			$v->addEvaluation($this);
		}

		return $this;
	}


	/**
	 * Get the associated Ecriteria object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Ecriteria The associated Ecriteria object.
	 * @throws     PropelException
	 */
	public function getEcriteria(PropelPDO $con = null)
	{
		if ($this->aEcriteria === null && ($this->ecriteria_id !== null)) {
			$this->aEcriteria = EcriteriaQuery::create()
				->filterByEvaluation($this) // here
				->findOne($con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aEcriteria->addEvaluations($this);
			 */
		}
		return $this->aEcriteria;
	}

	/**
	 * Declares an association between this object and a Metric object.
	 *
	 * @param      Metric $v
	 * @return     Evaluation The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMetric(Metric $v = null)
	{
		if ($v === null) {
			$this->setMetricId(NULL);
		} else {
			$this->setMetricId($v->getId());
		}

		$this->aMetric = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Metric object, it will not be re-added.
		if ($v !== null) {
			$v->addEvaluation($this);
		}

		return $this;
	}


	/**
	 * Get the associated Metric object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Metric The associated Metric object.
	 * @throws     PropelException
	 */
	public function getMetric(PropelPDO $con = null)
	{
		if ($this->aMetric === null && ($this->metric_id !== null)) {
			$this->aMetric = MetricQuery::create()->findPk($this->metric_id, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aMetric->addEvaluations($this);
			 */
		}
		return $this->aMetric;
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->site_id = null;
		$this->ecriteria_id = null;
		$this->metric_id = null;
		$this->value = null;
		$this->created_at = null;
		$this->updated_at = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all references to other model objects or collections of model objects.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect
	 * objects with circular references (even in PHP 5.3). This is currently necessary
	 * when using Propel in certain daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all referrer objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

		$this->aSite = null;
		$this->aEcriteria = null;
		$this->aMetric = null;
	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->exportTo(EvaluationPeer::DEFAULT_STRING_FORMAT);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseEvaluation:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		return parent::__call($name, $params);
	}

} // BaseEvaluation
